### PR TITLE
Add m2e metadata - support for Eclipse IDE

### PR DESCRIPTION
**Pull request by agabrys**
Hi,
I added support for Eclipse IDE. Now Eclipse users will not see `m2e` errors related with missing connector. I enabled incremental build for goals:
* `scss-lint`
* `scss-lint-report`
* `update-stylesheets`

I didn't add configuration for `help` and `watch` goals, because I think that people use those goals only in command line.

### CODE REVIEW

**Comment by agabrys** [comment]
Read more: https://wiki.eclipse.org/M2E_compatible_maven_plugins#Overview

**Comment by mprins** [comment]
Thanks for this; I don't use Eclipse myself, so I'll just take your word for it :+1:

**Comment by agabrys** [comment]
Thank you :)

**Comment by agabrys** [comment]
This PR has been corrected in [Fix m2e metadata - support for Eclipse IDE](/GeoDienstenCentrum/sass-maven-plugin/pull/113).

**Pull request merged**
