### PR TITLE
add parameter to specify a `compass.rb` configuration file for compass

### PR DESCRIPTION
**Pull request by StefanLiebenberg**
I needed a way to specify a compass config file location from the pom.xml, this was the solution.

### CODE REVIEW

**Comment by mprins** [comment]
Can you please stick to the indentation style, sign the contributing agreement and provide a test project? You can find example test projects in  `./src/test/projects` and create a copy or create your own.

**Comment by StefanLiebenberg** [comment]
i can take a look at doing that, but it probably will take a long time.

**Comment by StefanLiebenberg** [comment]
Also, how is the "contribution agreement" signed?

**Comment by mprins** [comment]
A link to the contribution agreement is available in the CONTRIBUTING.md document. We using clahub

**Comment by StefanLiebenberg** [comment]
changed all files as request, added test project. can't sign said agreement due to consistent error on page.

**Pull request merged**
